### PR TITLE
Navbar component

### PR DESCRIPTION
**Pull request by khalosmoscato**
## Description

- Created Logo and Navbar components.
- Uploaded logo as an SVG file in src/assets/Logo.svg
- All our components are mobile first, responsive, high contrast to help readability (for the Navbar we are using Black and White mainly, the logo is #FFC100)
- 
## Type of Change

- ✨ New feature, style (non-breaking change that adds functionality)
- 📄 Documentation changes (if none of the above apply)

## Checklist

- [✅] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas (if necessary)
- [✅] I have updated the documentation (if necessary)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing tests pass locally with my changes

### CODE REVIEW

**Review by jackcasstlesjones — CHANGES_REQUESTED** [review]
Please add these colours to the docs as a style guide and change the colour used in the logo (but thank you for using my fav)

```
#6F2DBD - Higlights (grape)

#FFD166 - Logo (yellow)

#1B2D2A - Text (gunmetal)

#629677 - Hero background and cards background (green)

#495D63 - Highlights (light grey)
```

**Review by william-man — APPROVED** [review]
Looks good. I like that the template presents our pr in a more structured way and that we are able to document our work in a dedicated file rather than flood our work with comments.

**Comment by khalosmoscato** [comment]
@jackcasstlesjones 
- Updated Logo colour
- Added colour palette to our README file

**Review by jackcasstlesjones — APPROVED** [review]
looks good!

**Pull request merged**
